In [96]:
import numpy as np
import pandas as pd

In [98]:
df = pd.read_csv("../metrics/ann_models.csv")
df.head()

,Epochs,Accuracy,F1 Score,Recall,Precision,MCC,Kappa
0,"for 75, 32, the results are:",[0.7925925925925926,0.732484,0.684524,0.787671,0.568191,0.5644826791612259]
1,"for 75, 64, the results are:",[0.7901234567901234,0.733542,0.696429,0.774834,0.563409,0.5612358046877988]
2,"for 75, 128, the results are:",[0.7975308641975308,0.743750,0.708333,0.782895,0.579068,0.5770935207823962]
3,"for 75, 256, the results are:",[0.7975308641975308,0.737179,0.684524,0.798611,0.578613,0.5740997229916898]
4,"for 75, 512, the results are:",[0.8,0.742857,0.696429,0.795918,0.583873,0.5804075054679406]

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Epochs     40 non-null     object
 1   Accuracy   40 non-null     object
 2   F1 Score   40 non-null     float64
 3   Recall     40 non-null     float64
 4   Precision  40 non-null     float64
 5   MCC        40 non-null     float64
 6   Kappa      40 non-null     object
dtypes: float64(4), object(3)
memory usage: 2.3+ KB

In [100]:
df.shape

(40, 7)

In [101]:
for i in range(len(df)):
    df['Accuracy'][i] = str(df['Accuracy'][i]).replace("[","")
    df['Kappa'][i] = str(df['Kappa'][i]).replace("]","")

C:\Users\asus_\AppData\Local\Temp\ipykernel_23072\3996114395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Accuracy'][i] = str(df['Accuracy'][i]).replace("[","")
C:\Users\asus_\AppData\Local\Temp\ipykernel_23072\3996114395.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Kappa'][i] = str(df['Kappa'][i]).replace("]","")

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Epochs     40 non-null     object
 1   Accuracy   40 non-null     object
 2   F1 Score   40 non-null     float64
 3   Recall     40 non-null     float64
 4   Precision  40 non-null     float64
 5   MCC        40 non-null     float64
 6   Kappa      40 non-null     object
dtypes: float64(4), object(3)
memory usage: 2.3+ KB

In [82]:
df.head()

,Epochs,Accuracy,F1 Score,Recall,Precision,MCC,Kappa
0,"for 75, 32, the results are:",0.7925925925925926,0.732484,0.684524,0.787671,0.568191,0.5644826791612259
1,"for 75, 64, the results are:",0.7901234567901234,0.733542,0.696429,0.774834,0.563409,0.5612358046877988
2,"for 75, 128, the results are:",0.7975308641975308,0.743750,0.708333,0.782895,0.579068,0.5770935207823962
3,"for 75, 256, the results are:",0.7975308641975308,0.737179,0.684524,0.798611,0.578613,0.5740997229916898
4,"for 75, 512, the results are:",0.8,0.742857,0.696429,0.795918,0.583873,0.5804075054679406

In [83]:
df['Accuracy'] = df['Accuracy'].astype(float)
df['Kappa'] = df['Kappa'].astype(float)

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Epochs     40 non-null     object
 1   Accuracy   40 non-null     float64
 2   F1 Score   40 non-null     float64
 3   Recall     40 non-null     float64
 4   Precision  40 non-null     float64
 5   MCC        40 non-null     float64
 6   Kappa      40 non-null     float64
dtypes: float64(6), object(1)
memory usage: 2.3+ KB

In [85]:
for i in range(len(df)):
    df['Epochs'][i] = str(df['Epochs'][i]).replace("for ","")
    df['Epochs'][i] = str(df['Epochs'][i]).replace(", the results are:","")
    df['Epochs'][i] = str(df['Epochs'][i]).replace(",","")

C:\Users\asus_\AppData\Local\Temp\ipykernel_23072\852015130.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Epochs'][i] = str(df['Epochs'][i]).replace("for ","")
C:\Users\asus_\AppData\Local\Temp\ipykernel_23072\852015130.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Epochs'][i] = str(df['Epochs'][i]).replace(", the results are:","")
C:\Users\asus_\AppData\Local\Temp\ipykernel_23072\852015130.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Epochs'][i] = str(df['Epochs'][i]).replace(",","")

In [86]:
df.head()

    Epochs  Accuracy  F1 Score    Recall  Precision       MCC     Kappa
0   75 32   0.792593  0.732484  0.684524   0.787671  0.568191  0.564483
1   75 64   0.790123  0.733542  0.696429   0.774834  0.563409  0.561236
2  75 128   0.797531  0.743750  0.708333   0.782895  0.579068  0.577094
3  75 256   0.797531  0.737179  0.684524   0.798611  0.578613  0.574100
4  75 512   0.800000  0.742857  0.696429   0.795918  0.583873  0.580408

In [87]:
df[['Epochs','Neurons']] = df.Epochs.str.split(expand=True)

In [88]:
df.head()

  Epochs  Accuracy  F1 Score    Recall  Precision       MCC     Kappa Neurons
0     75  0.792593  0.732484  0.684524   0.787671  0.568191  0.564483      32
1     75  0.790123  0.733542  0.696429   0.774834  0.563409  0.561236      64
2     75  0.797531  0.743750  0.708333   0.782895  0.579068  0.577094     128
3     75  0.797531  0.737179  0.684524   0.798611  0.578613  0.574100     256
4     75  0.800000  0.742857  0.696429   0.795918  0.583873  0.580408     512

In [89]:
df['Epochs'] = df['Epochs'].astype(int)
df['Neurons'] = df['Neurons'].astype(int)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Epochs     40 non-null     int32
 1   Accuracy   40 non-null     float64
 2   F1 Score   40 non-null     float64
 3   Recall     40 non-null     float64
 4   Precision  40 non-null     float64
 5   MCC        40 non-null     float64
 6   Kappa      40 non-null     float64
 7   Neurons    40 non-null     int32
dtypes: float64(6), int32(2)
memory usage: 2.3 KB

In [91]:
df['Sums'] = df['Accuracy'] + df['F1 Score'] + df['Recall'] + df['Precision'] + df['MCC'] + df['Kappa']

In [92]:
df.head()

,Epochs,Accuracy,F1 Score,Recall,Precision,MCC,Kappa,Neurons,Sums
0,75,0.792593,0.732484,0.684524,0.787671,0.568191,0.564483,32,4.129945
1,75,0.790123,0.733542,0.696429,0.774834,0.563409,0.561236,64,4.119574
2,75,0.797531,0.743750,0.708333,0.782895,0.579068,0.577094,128,4.188671
3,75,0.797531,0.737179,0.684524,0.798611,0.578613,0.574100,256,4.170558
4,75,0.800000,0.742857,0.696429,0.795918,0.583873,0.580408,512,4.199484

In [93]:
df = df.sort_values('Sums',ascending=False)

In [94]:
df.head()

,Epochs,Accuracy,F1 Score,Recall,Precision,MCC,Kappa,Neurons,Sums
39,250,0.812346,0.757962,0.708333,0.815068,0.609941,0.605961,512,4.309611
36,250,0.812346,0.757962,0.708333,0.815068,0.609941,0.605961,64,4.309611
34,225,0.812346,0.753247,0.690476,0.828571,0.610397,0.603861,512,4.298898
38,250,0.812346,0.753247,0.690476,0.828571,0.610397,0.603861,256,4.298898
20,175,0.807407,0.751592,0.702381,0.808219,0.599504,0.595591,32,4.264695

In [95]:
df

,Epochs,Accuracy,F1 Score,Recall,Precision,MCC,Kappa,Neurons,Sums
39,250,0.812346,0.757962,0.708333,0.815068,0.609941,0.605961,512,4.309611
36,250,0.812346,0.757962,0.708333,0.815068,0.609941,0.605961,64,4.309611
34,225,0.812346,0.753247,0.690476,0.828571,0.610397,0.603861,512,4.298898
38,250,0.812346,0.753247,0.690476,0.828571,0.610397,0.603861,256,4.298898
20,175,0.807407,0.751592,0.702381,0.808219,0.599504,0.595591,32,4.264695
32,225,0.807407,0.750000,0.696429,0.812500,0.599552,0.594875,128,4.260763
28,200,0.807407,0.750000,0.696429,0.812500,0.599552,0.594875,256,4.260763
37,250,0.804938,0.750789,0.708333,0.798658,0.594365,0.591489,128,4.248571
23,175,0.804938,0.749206,0.702381,0.802721,0.594295,0.590768,256,4.244309
9,100,0.804938,0.749206,0.702381,0.802721,0.594295,0.590768,512,4.244309
33,225,0.804938,0.747604,0.696429,0.806897,0.594292,0.590044,256,4.240204
30,225,0.804938,0.747604,0.696429,0.806897,0.594292,0.590044,32,4.240204
27,200,0.804938,0.747604,0.696429,0.806897,0.594292,0.590044,128,4.240204
26,200,0.804938,0.747604,0.696429,0.806897,0.594292,0.590044,64,4.240204
35,250,0.804938,0.747604,0.696429,0.806897,0.594292,0.590044,32,4.240204
31,225,0.804938,0.745981,0.690476,0.811189,0.594359,0.589318,64,4.236261
19,150,0.804938,0.745981,0.690476,0.811189,0.594359,0.589318,512,4.236261
15,150,0.804938,0.744337,0.684524,0.815603,0.594495,0.588589,32,4.232486
13,125,0.802469,0.746835,0.702381,0.797297,0.589118,0.585953,256,4.224054
29,200,0.804938,0.739274,0.666667,0.829630,0.595341,0.586387,512,4.222236
24,175,0.802469,0.745223,0.696429,0.801370,0.589066,0.585222,512,4.219778
22,175,0.802469,0.745223,0.696429,0.801370,0.589066,0.585222,128,4.219778
12,125,0.802469,0.745223,0.696429,0.801370,0.589066,0.585222,128,4.219778
18,150,0.802469,0.741935,0.684524,0.809859,0.589167,0.583751,256,4.211705
8,100,0.800000,0.744479,0.702381,0.791946,0.583972,0.581147,256,4.203926
21,175,0.800000,0.742857,0.696429,0.795918,0.583873,0.580408,64,4.199484
4,75,0.800000,0.742857,0.696429,0.795918,0.583873,0.580408,512,4.199484
7,100,0.800000,0.739550,0.684524,0.804196,0.583873,0.578921,128,4.191063
2,75,0.797531,0.743750,0.708333,0.782895,0.579068,0.577094,128,4.188671
14,125,0.797531,0.738854,0.690476,0.794521,0.578629,0.574852,512,4.174862
3,75,0.797531,0.737179,0.684524,0.798611,0.578613,0.574100,256,4.170558
11,125,0.795062,0.738170,0.696429,0.785235,0.573580,0.570805,64,4.159280
17,150,0.795062,0.736508,0.690476,0.789116,0.573450,0.570047,128,4.154659
6,100,0.792593,0.734177,0.690476,0.783784,0.568304,0.565251,64,4.134584
10,125,0.792593,0.734177,0.690476,0.783784,0.568304,0.565251,32,4.134584
0,75,0.792593,0.732484,0.684524,0.787671,0.568191,0.564483,32,4.129945
25,200,0.792593,0.732484,0.684524,0.787671,0.568191,0.564483,32,4.129945
5,100,0.792593,0.730769,0.678571,0.791667,0.568143,0.563712,32,4.125455
1,75,0.790123,0.733542,0.696429,0.774834,0.563409,0.561236,64,4.119574
16,150,0.785185,0.720257,0.666667,0.783217,0.552415,0.547730,64,4.055471